GLOBAL_STYLES = (""
    "QMainWindow {background-color: #fff;}"
    "QPushButton {"
    "border-radius: 25;"
    "background-color: white;"
    "}"
    "QPushButton::hover {"
    "border-radius: 25;"
    "background-color: #eee;"
    "}")
